apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
- service.yaml

commonLabels:
  app.kubernetes.io/component: redis
  app.kubernetes.io/instance: redis
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/name: redis
  app.kubernetes.io/part-of: example-3tier-app
  app.kubernetes.io/version: latest
