apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

commonLabels:
  app.kubernetes.io/component: back-end
  app.kubernetes.io/instance: api
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/name: api
  app.kubernetes.io/part-of: example-3tier-app
  app.kubernetes.io/version: latest
